### ISSUE TITLE
readcomments partial error when rendering

### ISSUE THREAD

**Issue by jbz-dev** [saimiri/hugojoco#1]
`ERROR: 2017/02/05 18:30:21 general.go:236: partials/readcomments.html is an incomplete or empty template`

That's the error I have when using your configuration.

**Comment by saimiri** [comment]
Sounds like it can't find the file. Do you have the `readcomments.html` file in the same directory as the parent template?

**Comment by jbz-dev** [comment]
Yes I do.

Ans d'or what I understood I created related folder in `static/comments/` named like m'y blog posts. And in those folders I stored comments in JSON files like `comment-1.json` `comment-2.json`

**Comment by saimiri** [comment]
Actually in the example the `comments/` directory is assumed to be on the same level as `content/` and not under the `static/` directory, but the error message doesn't sound like that's the problem.

Is this how you try to load the `readcomments.html`?

```
{{ partial "readcomments.html" . }}
```

**Comment by jbz-dev** [comment]
Yes that's how I load `readcomments` partial.

I stricly copied your two partials in this repo, added them to `/layouts/partials` on my Hugo  folder. Then when I do `hugo serve` that's what I have

**Comment by saimiri** [comment]
Unfortunately, this is still more on the proof-of-concept level and as such may not work by just dropping it in.

If you copied the example files verbatim and you still have the comments in `static/comments`, then that could be the problem. I faintly recall getting some confusing error messages if the code in a template failed.

I'd try first moving the `comments/` to the parent directory, so it's in the Hugo root. `static` is meant for stuff that Hugo shouldn't touch but move to the web root as it is, anyway.

If it still doesn't work I suggest you remove all the code from `readcomments.html` and put just plain html in it. If the error disappears, then the problem is in that file and we can look into it in more detail. If not, it's somewhere else.

**Comment by jbz-dev** [comment]
I tried again yesterday and can't find more indications about the error. However I managed to create a simple static comments system using YAML data files. That's really simple but very flexible :)

Thanks anyway for ideas, you started something in me ;)

**Comment by saimiri** [comment]
Hey, that's great! =) I'm happy something good came out of this, even if _hugojoco_ didn't work out for you.

Let me know if you put your system out in the open. Maybe I can snatch some ideas for myself. ;)
